[package]
name = "spam-align"
version = "0.1.0"
authors = ["robinwilliam.hundt <robinwilliam.hundt@stud.uni-goettingen.de>"]
edition = "2018"

[dependencies]
bio = "0.26.1"
serde_derive = "1.0.91"
serde = "1.0.91"
serde-xml-rs = "0.3.1"
itertools = "0.8.0"
rayon = "1.0.3"
structopt = "0.2.16"
ndarray = "0.12.1"
rand = "0.7.0"
fxhash = "0.2.1"
smallvec = "0.6.11"
petgraph = "0.4.13"
